import React, { useCallback } from 'react';
import { Dialog, DialogTitle, DialogContent, DialogActions, Button, Typography, Box, List, ListItem, ListItemIcon, ListItemText } from '@mui/material';
import WarningAmberIcon from '@mui/icons-material/WarningAmber';
import { ScriptType } from '../types';

interface ExecutionWarningModalProps {
  isOpen: boolean;
  onClose: () => void;
  script: string;
  scriptType: ScriptType;
}

const ExecutionWarningModal: React.FC<ExecutionWarningModalProps> = ({ isOpen, onClose, script, scriptType }) => {
  const handleCopyAndClose = useCallback(() => {
    navigator.clipboard.writeText(script).then(() => {
      onClose();
    });
  }, [script, onClose]);

  return (
    <Dialog open={isOpen} onClose={onClose} aria-labelledby="alert-dialog-title">
      <DialogTitle id="alert-dialog-title" sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
        <WarningAmberIcon color="warning" />
        Security Warning
      </DialogTitle>
      <DialogContent dividers>
        <Typography gutterBottom>
          Scripts generated by AI may have unintended consequences. Always review and understand a script before running it, especially with administrative privileges.
        </Typography>
        <Typography variant="body2" sx={{ p: 2, backgroundColor: 'background.default', borderRadius: 1, my: 2 }}>
          <strong>Note:</strong> This application runs in a sandboxed browser environment and <Typography component="span" color="warning.main" fontWeight="bold">cannot</Typography> execute scripts directly or capture their output.
        </Typography>
        <Typography variant="h6" component="h4" gutterBottom>To run this script safely:</Typography>
        <List dense>
            <ListItem>
                <ListItemText primary="1. Review the script code carefully on the main page." />
            </ListItem>
            <ListItem>
                <ListItemText primary="2. Click 'Copy Script & Close' below." />
            </ListItem>
            <ListItem>
                <ListItemText primary={
                    <>3. Open a <Typography component="span" color="primary" fontWeight="bold">{scriptType === ScriptType.POWERSHELL ? 'PowerShell terminal (as Administrator if needed)' : 'Bash terminal'}</Typography>.</>
                } />
            </ListItem>
             <ListItem>
                <ListItemText primary="4. Paste and run the script." />
            </ListItem>
        </List>
      </DialogContent>
      <DialogActions>
        <Button onClick={onClose} color="inherit">Cancel</Button>
        <Button onClick={handleCopyAndClose} variant="contained" autoFocus>
          Copy Script & Close
        </Button>
      </DialogActions>
    </Dialog>
  );
};

export default ExecutionWarningModal;